env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-unused-vars": "warn",
    "no-unused-vars": "off",

    "@typescript-eslint/explicit-module-boundary-types": "off",

    "@typescript-eslint/no-explicit-any": "off",

    "@typescript-eslint/no-empty-interface":
      ["off", { "allowSingleExtends": true }],
  }
